# basic options
title: Your awesome title
author: Yurikan4ik
email: your-email@domain.com
description: A wonderful site
twitter_username: Unsuccessful96
github_username:  Yurikan4ik

# Build settings
markdown: kramdown
theme: minima
